### PR TITLE
Fix building on linux (and possibly on windows)

### PR DESCRIPTION
**Pull request by dcbaker**
This pull corrects the build on linux in a couple of ways:

First it stops falling back to a dll.a file, which I assume was actually meant as a fallback for windows

Second, It uses find_package with the config option for assimp. This config file should not be imported (unlike what is suggested by #26), it is provided by the upstream and if assimp is installed the cmake-config should be properly installed and available on the system. This should be faster and more robust than the current find_libraries approach.

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Thx!

**Comment by CapsAdmin** [comment]
This works for me on kubuntu 15 as well. I had to do "export ASSIMP_DIR=*path to assimp git repo*" though.

**Comment by dcbaker** [comment]
Now that I look back at it, I think that the first patch might be wrong. ld gave me an error about libass.dll.a that made me think it wasn't a linux object, but it is a .a file?

@CapsAdmin, did you have to do that before or after my patches?

**Comment by CapsAdmin** [comment]
Compiling never worked for me before. See #33

**Comment by SaschaWillems** [comment]
Yes, libassimp.dll.a is not a linux file and was a mistake. I used this to check if all projects compile fine on Winodws with MinGW.

**Comment by SaschaWillems** [comment]
Sadly this won't work for me on linux anymore. It can't locate assimpd, even though I installed libssimp-dev.

I'm on Ubuntu. Any ideas? I'd prefer having a CMakeLists.txt that works out of the box :/

**Comment by dcbaker** [comment]
hmmmm, it appears that for some reason ubuntu, (or maybe debian?) doesn't install the cmake-config files. Let me do some more digging, at the worst I'll write a FindLibassimp.cmake that does the proper falling back.

**Pull request merged**
