### PR TITLE
Make glsl and hlsl shader directories sit side-by-side

### LINKED ISSUE #723: Proposal: Shader directory restructure
With [HLSL shaders now landed](https://github.com/SaschaWillems/Vulkan/pull/718), I propose we re-jig the shader directories a bit.

Currently we have:

```
data/
 ┣━━ hlsl/
 ┃    ┣━━ base/
 ┃    ┃    ┣━━ textoverlay.frag
 ┃    ┃    ┣━━ textoverlay.vert
 ┃    ┃    ┣━━ uioverlay.frag
 ┃    ┃    ┗━━ uioverlay.vert
 ┃    ┣━━ bloom/
 ┃    ┣━━ computecloth/
 ┃    ┃   ...
 ┃    ┣━━ viewportarray/
 ┃    ┣━━ vulkanscene/
 ┃    ┣━━ compile.py
 ┃    ┗━━ README.md
 ┣━━ models/
 ┣━━ shaders/
 ┃    ┣━━ base/
 ┃    ┃    ┣━━ generate-spirv.bat
 ┃    ┃    ┣━━ textoverlay.frag
 ┃    ┃    ┣━━ textoverlay.frag.spv
 ┃    ┃    ┣━━ textoverlay.vert
 ┃    ┃    ┣━━ textoverlay.vert.spv
 ┃    ┃    ┣━━ uioverlay.frag
 ┃    ┃    ┣━━ uioverlay.frag.spv
 ┃    ┃    ┣━━ uioverlay.vert
 ┃    ┃    ┗━━ uioverlay.vert.spv
 ┃    ┣━━ bloom/
 ┃    ┣━━ computecloth/
 ┃    ┃   ...
 ┃    ┣━━ viewportarray/
 ┃    ┣━━ vulkanscene/
 ┃    ┗━━ compileshaders.py
 ┃ ...
```

What I'd like to propose is:
* We move the current content of `data/shaders` to `data/shaders/glsl`.
* We move `data/hlsl` to `data/shaders/hlsl`
* We emit the HLSL `.spv` files in the `data/shaders/hlsl/*/` directories instead of replacing those in `glsl`.
* We add a run time flag to pick `glsl` or `hlsl` based shaders (defaulting to `glsl`)

The directory structure would then look like:

```
data/
 ┣━━ models/
 ┣━━ shaders/
 ┃    ┣━━ hlsl/
 ┃    ┃    ┣━━ base/
 ┃    ┃    ┃    ┣━━ textoverlay.frag
 ┃    ┃    ┃    ┣━━ textoverlay.frag.spv
 ┃    ┃    ┃    ┣━━ textoverlay.vert
 ┃    ┃    ┃    ┣━━ textoverlay.vert.spv
 ┃    ┃    ┃    ┣━━ uioverlay.frag
 ┃    ┃    ┃    ┣━━ uioverlay.frag.spv
 ┃    ┃    ┃    ┣━━ uioverlay.vert
 ┃    ┃    ┃    ┗━━ uioverlay.vert.spv
 ┃    ┃    ┣━━ bloom/
 ┃    ┃    ┣━━ computecloth/
 ┃    ┃    ┃   ...
 ┃    ┃    ┣━━ viewportarray/
 ┃    ┃    ┣━━ vulkanscene/
 ┃    ┃    ┗━━ compile.py
 ┃    ┃
 ┃    ┗━━ glsl/
 ┃         ┣━━ base/
 ┃         ┃    ┣━━ generate-spirv.bat
 ┃         ┃    ┣━━ textoverlay.frag
 ┃         ┃    ┣━━ textoverlay.frag.spv
 ┃         ┃    ┣━━ textoverlay.vert
 ┃         ┃    ┣━━ textoverlay.vert.spv
 ┃         ┃    ┣━━ uioverlay.frag
 ┃         ┃    ┣━━ uioverlay.frag.spv
 ┃         ┃    ┣━━ uioverlay.vert
 ┃         ┃    ┗━━ uioverlay.vert.spv
 ┃         ┣━━ bloom/
 ┃         ┣━━ computecloth/
 ┃         ┃   ...
 ┃         ┣━━ viewportarray/
 ┃         ┣━━ vulkanscene/
 ┃         ┗━━ compile.py
 ┃ ...
```

If the general consensus is positive, I'll put up a PR to do this.

### PR DESCRIPTION
**Pull request by ben-clayton**
And add a new command line flag for picking between them (`-s` or `--shaders`).

This PR does everything proposed in #723.

Fixes #723

### CODE REVIEW

**Comment by SaschaWillems** [comment]
This looks mostly good to me after an initial quick review. One thing I didn't see in this PR: Did you also change the Android gradle files? They copy over the shader and won't work with the new structure.

**Comment by ben-clayton** [comment]
> One thing I didn't see in this PR: Did you also change the Android gradle files? They copy over the shader and won't work with the new structure.

Great spot. No I hadn't, but I've now fixed them up.
I also noticed there were a few dead links in the markdown / comments which are now also fixed up.

I amended the changes and force-pushed. Each change should build and work incrementally.

**Comment by eloj** [comment]
This is a large PR so maybe I missed it, but it may be worth documenting the expectations regarding contributions for new samples. I.e it almost seems codified now that all new samples must come with both glsl and hlsl shaders.

**Comment by ben-clayton** [comment]
> This is a large PR so maybe I missed it, but it may be worth documenting the expectations regarding contributions for new samples

I guess this is up to @SaschaWillems to decide - he may not want to block GLSL contributions if the author is not willing / able to contribute corresponding HLSL changes (for example, testing involves also building `dxc`, which may be more work than people are willing to make).

FWIW, the HLSL shaders existed before this PR - this just reshuffles the directories so they make more sense.

I'm happy to add documentation if we want to agree on policies around this. I'd probably suggest doing so in a new PR to avoid bloating this further :)

**Comment by eloj** [comment]
It's probably a non-issue, I don't know how rare external submissions are, especially now with the official Khronos spin-off, so probably shouldn't have brought it up.

**Comment by ben-clayton** [comment]
> so probably shouldn't have brought it up

Not at all. It's a great point to make.

If we (Google) are the only ones to use the HLSL shaders, it may be fair for us to take on the work to update these as and when needed, but with this approach, there will be periods of time when the HLSL side of things will be wrong / broken.

Nobody likes a broken sample.

**Comment by SaschaWillems** [comment]
I see HLSL as an optional feature for new sample. I haven't done much with it myself, so if I add new samples it may take some time before they support HLSL.

**Comment by SaschaWillems** [comment]
Just gave this a spin on Windows and Android and all samples I tested worked as expected. Will merge this.

Thanks again for you contributions. Your work is very much appreciated :)

**Comment by ben-clayton** [comment]
You're very welcome :)

**Pull request merged**
