### PR TITLE
Added FPS values to show on console

### PR DESCRIPTION
**Pull request by MuraliSridhar**
Hi Sascha Willems,

To get the FPS on terminal , I made following changes,
Please look if you can have on your repo.

Thanks,
Murali

### CODE REVIEW

**Comment by SaschaWillems** [comment]
While this works I don't see what's the value of this. FPS values are already displayed. Can you explain why you would need this?

**Comment by citrix123** [comment]
I Guess for saving / Extract FPS this is good. Also it can help the API Developers to do regression as well.
We can optimize it more, Some thing like Benchmarks . Eg: Glmark2 , unigine etc

Thanks,
Rahul

**Comment by SaschaWillems** [comment]
See #269, I'll be adding performance metrics and benchmark mode with a result file output in a future update.

**Comment by citrix123** [comment]
Looks Cool !!

**Pull request closed without merging**
