### PR TITLE
Update scenerendering.cpp

### PR DESCRIPTION
**Pull request by liuhongyi0101**
When merging indexes, we need to consider the number of vertices that have been merged

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Can you elaborate? Does this crash with the current version of the sample?

**Comment by liuhongyi0101** [comment]
the current version of the sample is right, but when I run your code with sponza , some of the models fail to be rendered.

**Comment by liuhongyi0101** [comment]
> Can you elaborate? Does this crash with the current version of the sample?
the current version of the sample is right, but when I run your code with sponza , some of the models fail to be rendered.

**Comment by liuhongyi0101** [comment]
> Can you elaborate? Does this crash with the current version of the sample?

the current version of the sample is right, but when I run your code with sponza , some of the models fail to be rendered.

**Comment by liuhongyi0101** [comment]
> Can you elaborate? Does this crash with the current version of the sample?

Replaced with sponza model, some models cannot be rendered，Isn't this a bug?   I reference your project  [https://github.com/SaschaWillems/VulkanSponza ]，It is right 。

**Comment by SaschaWillems** [comment]
Sorr  for the late reply. Just checked and Sponza didn't work for me either. I just pushed a fix that makes scenes other than Sibenik (like Sponza) to render properly witht that sample.

**Comment by liuhongyi0101** [comment]
Fixes rendering for other models like sponza

> Sorr for the late reply. Just checked and Sponza didn't work for me either. I just pushed a fix that makes scenes other than Sibenik (like Sponza) to render properly witht that sample.

It's ok，The problem is solved

**Pull request closed without merging**
