### PR TITLE
wayland: Port to xdg-shell stable

### PR DESCRIPTION
**Pull request by soreau**
Many wayland compositors do not support the deprecated wl_shell protocol but support xdg-shell protocol. This means that the vulkan demos fail to run in such environments. This changes the protocol used from the deprecated wl_shell to the xdg-shell stable protocol, which is the protocol clients are expected to use and compositors are expected to implement.

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Can you please add some description as to what this PR does? Will it break something, or will it still work with ever wayland distro?

**Comment by soreau** [comment]
If you look [here](https://people.freedesktop.org/~whot/wayland-doxygen/wayland/Server/page_iface_wl_shell.html) for instance, you can see that wl_shell is a deprecated protocol. I do not have a list of what compositors support xdg-shell stable but I think gnome and sway do and I know wayfire does.

**Comment by soreau** [comment]
Additionally, "Applications are recommended to move on to the stable xdg-shell version." from [a post](https://lists.freedesktop.org/archives/wayland-devel/2018-November/039670.html) by the lead wayland developer.

**Comment by soreau** [comment]
- Rebased on master
- Removed newline whitespace problems

**Comment by SaschaWillems** [comment]
Thanks for the clarification and your PR. Looks good to me 👍

**Pull request merged**
