### PR TITLE
FPS counter is not visible on Linux/XCB and nvidia drivers

### PR DESCRIPTION
**Pull request by zaps166**
Add missing ```xcb_flush()```, see the example: http://www.x.org/archive/X11R7.7/doc/man/man3/xcb_change_property.3.xhtml :)

### CODE REVIEW

**Comment by zaps166** [comment]
Hmm, without this flush the window title won't change on nvidia drivers, so the FPS counter is invisible on Linux (AFAIK it works on Intel drivers, but not on nvidia). The XCB documentation also shows that flush must be called after changing the window title. Qt also uses flush after changing the window title: https://github.com/qtproject/qtbase/blob/5.6/src/plugins/platforms/xcb/qxcbwindow.cpp#L1543

**Comment by SaschaWillems** [comment]
Sorry for the late reply. I'm currently writing an example for rendering text as an overlay (using a second render pass) to the existing scene and I plan on adding this functionality to the example base class later on, so that the examples no longer use the window title bar to report performance numbers.

**Comment by zaps166** [comment]
Ok, so I'm waiting for this feature :)

**Comment by SaschaWillems** [comment]
The examples use a text overlay to display a fps counter, so no more need to put this into a window title.

**Comment by zaps166** [comment]
Ok, but anyway it still tries to update a window title, but it doesn't work (wasting CPU time, inconsistency between drivers) :)

**Comment by SaschaWillems** [comment]
Yes, I'm currently doing some refactoring on the example base class and will address that too.

**Pull request closed without merging**
