### PR TITLE
Added table of contents + Ports

### PR DESCRIPTION
**Pull request by elect86**
I added a table of content for an easier browsing of the README plus an appended section mentioning ports like mine

### CODE REVIEW

**Comment by elect86** [comment]
> Thx for the PR. Please give me some time to review it.

You are welcome, sure Sascha.

> Also note that I'm not to keen on adding ports the landing readme.

uhm, not even in other page maybe?

**Comment by elect86** [comment]
Removed unused line of code

**Comment by SaschaWillems** [comment]
Can you remove the change you made to the imgui example and the link to the port? I'll merge it then, and as for adding ports maybe open up an issue where people can add links to their own ports?

**Comment by elect86** [comment]
Ok, done

**Pull request merged**
