### PR TITLE
Build base/*.cpp as a library to prevent recompiling it multiple times

### PR DESCRIPTION
**Pull request by jpbruyere**
modifié :         CMakeLists.txt
	nouveau fichier : base/CMakeLists.txt

### CODE REVIEW

**Comment by jpbruyere** [comment]
failed with gcc on travis => closed

**Comment by SaschaWillems** [comment]
It looks like there may be just a define missing (xcb). Moving base to a shared library is something I wanted to work on multiple times but never actually got around doing so. I'll try to take a look at why this only fails with gcc on travis (and works fine with clang).

**Comment by jpbruyere** [comment]
I've enabled travis for my fork, I'll make some tests. But for win and android builds I can't check that it's working fine.

**Comment by jpbruyere** [comment]
Now I think it's ok, It compiles fine. I'm trying to reopen the pull request but I've reset several commits and make some forced pushes. Maybe I'll have to make another pull request. let's try...

**Pull request closed without merging**
